name: GitHub CI / CD Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - run: echo "Buid işlemi başladı"
      - run: pwd
      - run: echo "Build işlemi tamamlandı"
